service: chatroom

provider:
  name: aws
  stage: dev
  websocketApiRouteSelectionExpression: $request.body.action

plugins:
  - serverless-websockets-plugin
  - serverless-plugin-typescript

functions:
  connect:
    handler: src/handlers/connect.handler
    events:
     - websocket:
        routeKey: $connect
  dissconect:
    handler: src/handlers/dissconect.handler
    events:
      - websocket:
        routeKey: $disconnect
  default:
    handler: src/handlers/default.handler
    events:
      - websocket:
        routeKey: $default
  listRooms:
    handler: src/handlers/listRooms.handler
    events:
      - websocket:
        routeKey: listRooms